// Dados Oficiais da DRE e Resumo Orçamento x Real da Obra Atrium Select
// Extraídos diretamente da planilha oficial: T:\ANÁLISES (TIAGO E TANIA)\Orçamentos\Atrium\ATRIUM - Planejamento e Controle de Obra (PCO) - SET 26 - IMPORT.xlsx

export interface DreItem {
  id: string;
  rowNumber: number;
  name: string;
  orcado: number;
  realizado: number;
  variacao: number;
  percentRealizado: number;
  level: number;
  isGroup: boolean;
  isTotal: boolean;
  category: string;
  subgroup: string;
}

export const ATRIUM_DRE_SUMMARY = {
  receita: {
    orcadoBruto: 55206000.00,
    realizadoBruto: 4789007.29,
    variacaoBruta: -50416992.71,
    percentBruto: 8.68,
    deducoesOrcado: 2208240.00,
    deducoesRealizado: 228373.95,
    liquidaOrcado: 52997760.00,
    liquidaRealizado: 4560633.34,
    liquidaPercent: 8.61,
  },
  custoObra: {
    orcado: 25705359.47,
    realizado: 11292416.61,
    variacao: -14412942.86,
    percent: 43.93,
    materiaisServicos: { orcado: 15715662.40, realizado: 6764032.26, percent: 43.04 },
    maoDeObra: { orcado: 8897338.35, realizado: 3730363.01, percent: 41.93 },
    admObra: { orcado: 925480.00, realizado: 600933.62, percent: 64.93 },
    terrenosLegalizacoes: { orcado: 166878.72, realizado: 197087.72, percent: 118.10 },
  },
  despesas: {
    orcado: 5751391.28,
    realizado: 2755854.03,
    variacao: -2995537.25,
    percent: 47.92,
    impostosReceita: { orcado: 2208240.00, realizado: 228373.95, percent: 10.34 },
    comissoesVendas: { orcado: 2484270.00, realizado: 596914.20, percent: 24.03 },
    comerciaisMkt: { orcado: 1104120.00, realizado: 278054.89, percent: 25.18 },
    administrativasSede: { orcado: 61500.00, realizado: 284249.00, percent: 462.19 },
    terceirizadosJuridico: { orcado: 0, realizado: 819541.46 },
    posObra: { orcado: 0, realizado: 220044.30 },
  },
  resultadoFinanceiro: {
    // Fórmula: Receitas de Vendas (R$ 55.206.000,00) - Custos de Obra (R$ 25.705.359,47) - Despesas Totais (R$ 5.751.391,28) = R$ 23.749.249,25
    resultadoOperacionalOrcado: 23749249.25,
    // Realizado: R$ 4.789.007,29 - R$ 11.292.416,61 - R$ 2.755.854,03 = -R$ 9.259.263,35
    resultadoOperacionalRealizado: -9259263.35,
    margemOperacionalOrcada: 43.02,
    margemOperacionalRealizada: -193.34,
    resultadoNaoOperacionalRealizado: -4432.25,
    resultadoInvestimentoRealizado: -186278.78,
    resultadoCaixaOrcado: 23704010.53,
    resultadoCaixaRealizado: -9449474.38,
    explicacaoCiclo: 'O resultado realizado acumulado reflete o ciclo operacional e financeiro da construção civil (fase de maior intensidade de custos civis de fundação, estrutura e alvenaria antes do ingresso concentrado das receitas de financiamento e quitação na entrega das chaves).',
  },
};

// Contas pertencentes estritamente ao Orçamento da Obra (Planilha1 / BASE ORÇAMENTO)
// Totalizam exatamente R$ 25.705.359,47
export const ATRIUM_OBRA_ACCOUNTS: string[] = [
  "Agua & Esgoto - Obra",
  "Alimentação de Pessoal - Obra",
  "Aluguel E Manut. De Maq. Equip E Móveis - Obra",
  "ALVENARIA E PAINÉIS",
  "CONTROLE TECNOLÓGICO",
  "Cópias E Impressões - Obra",
  "Cursos e Treinamentos",
  "Desmatamento/Demolição",
  "ELEVADORES",
  "ENERGIA ELÉTRICA - OBRA",
  "EPC(Proteção Coletiva) - Obra",
  "ESQUADRIAS DE ALUMÍNIO",
  "ESQUADRIAS DE MADEIRA",
  "ESTRUTURA DE CONCRETO",
  "Fardamentos/EPI - Obra",
  "FERRAMENTAS",
  "FORROS",
  "Fretes - Obra",
  "FUNDAÇÕES",
  "IMPERMEABILIZAÇÃO(MAT+M.O.)",
  "Instalação De Ar Condicionado(MAT+M.O.)",
  "INSTALAÇÃO DO CANTEIRO",
  "Instalações De Gás(MAT+M.O.)",
  "INSTALAÇÕES ELÉTRICAS(MAT+M.O.)",
  "INSTALAÇÕES HIDROSSANITÁRIAS(MAT+M.O.)",
  "INSTALAÇÕES INCÊNDIO(MAT+M.O.)",
  "Instalações Telefônicas(MAT+M.O.)",
  "IPTU - OBRA",
  "Licenças e Legalizações",
  "Limpeza De Obra",
  "Louças E Metais",
  "Mármores E Granitos",
  "Outorga/Operação Urbana/Solo Criado",
  "Paisagismo/Urbanismo/Decoração/Acessórios",
  "PINTURA (MAT+M.O.)",
  "PISOS(MAT+M.O.)",
  "Pré-moldados",
  "PROJETOS(ARQ./INST./ESTRUTURAL ETC)",
  "REVESTIMENTO EXTERNO",
  "REVESTIMENTO INTERNO",
  "Serviço de Segurança de Canteiro",
  "SONDAGEM E TOPOGRAFIA",
  "STAND DE VENDAS/AP.DECORADO(CONSTRUÇÃO)",
  "Telefonia/Internet - Obra",
  "TERRAPLANAGEM",
  "TRANSPORTE DE PESSOAL - OBRA",
  "Salários - Obra"
];

// Regras De-Para consolidadas (86 contas de destino)
export const ATRIUM_DEPARA_RULES = [
  {
    "origem": "##Acordos, Condenações Trabalhista, Pericias##",
    "destino": "Depósito Judicial e Condenações"
  },
  {
    "origem": "##Ajustes De Caixa##",
    "destino": "-"
  },
  {
    "origem": "##Assist.Medica/Odotonlogica##",
    "destino": "Salários - Obra"
  },
  {
    "origem": "##Despesas Diversas##",
    "destino": "DESPESAS COM PERDAS"
  },
  {
    "origem": "##FGTS RESCISORIO##",
    "destino": "Salários - Obra"
  },
  {
    "origem": "##Manut. Máq/Equip.##",
    "destino": "Aluguel E Manut. De Maq. Equip E Móveis - Obra"
  },
  {
    "origem": "13º. Salário - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Ação e Eventos de Relacionamento Comerciais",
    "destino": "Ação e Eventos de Relacionamento Comerciais"
  },
  {
    "origem": "Admissões e Rescisões - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Agua & Esgoto - Obra",
    "destino": "Agua & Esgoto - Obra"
  },
  {
    "origem": "Alimentação de Pessoal - Obra",
    "destino": "Alimentação de Pessoal - Obra"
  },
  {
    "origem": "Aluguel E Manut. De Maq. Equip E Móveis - Obra",
    "destino": "Aluguel E Manut. De Maq. Equip E Móveis - Obra"
  },
  {
    "origem": "Alvenaria E Painéis",
    "destino": "ALVENARIA E PAINÉIS"
  },
  {
    "origem": "Aquisição de Computadores e Periféricos",
    "destino": "Aquisição de Computadores e Periféricos"
  },
  {
    "origem": "Aquisição De Máquinas e Equipamentos",
    "destino": "Aquisição De Máquinas e Equipamentos"
  },
  {
    "origem": "Aquisição de Móveis e Utensílios",
    "destino": "Aquisição de Móveis e Utensílios"
  },
  {
    "origem": "Aquisição De Terrenos",
    "destino": "Aquisição De Terrenos"
  },
  {
    "origem": "Assesorias de Marketing",
    "destino": "Assesorias de Marketing"
  },
  {
    "origem": "Benefício de Pessoal Adm",
    "destino": "SALARIOS DO ADM"
  },
  {
    "origem": "Beneficios de Pessoal - Obra",
    "destino": "SALARIOS DO ADM"
  },
  {
    "origem": "Benefícios e Retiradas da Diretoria",
    "destino": "Benefícios e Retiradas da Diretoria"
  },
  {
    "origem": "Brindes",
    "destino": "Brindes"
  },
  {
    "origem": "COFINS",
    "destino": "COFINS"
  },
  {
    "origem": "Combustível e Lubrificantes",
    "destino": "Combustível e Lubrificantes"
  },
  {
    "origem": "Comissão De Corretores",
    "destino": "Comissão De Corretores"
  },
  {
    "origem": "Confraternizações e Eventos Internos Adm",
    "destino": "Confraternizações e Eventos Internos Adm"
  },
  {
    "origem": "Contribuições Sindicais - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Controle Tecnológico",
    "destino": "Controle Tecnológico"
  },
  {
    "origem": "Cópias E Impressões - Obra",
    "destino": "Cópias E Impressões - Obra"
  },
  {
    "origem": "Correios/Malote - Adm",
    "destino": "Correios/Malote - Adm"
  },
  {
    "origem": "CSLL",
    "destino": "CSLL"
  },
  {
    "origem": "Cursos e Treinamentos",
    "destino": "Cursos e Treinamentos"
  },
  {
    "origem": "Custas Processuais",
    "destino": "Custas Processuais"
  },
  {
    "origem": "Depósito Judicial e Condenações",
    "destino": "Depósito Judicial e Condenações"
  },
  {
    "origem": "Desmatamento/Demolição",
    "destino": "Desmatamento/Demolição"
  },
  {
    "origem": "Despachantes",
    "destino": "Despachantes"
  },
  {
    "origem": "Despesas com Material de Copa e Limpeza - Adm",
    "destino": "Despesas com Material de Copa e Limpeza - Adm"
  },
  {
    "origem": "Devoluções/Distratos de Vendas",
    "destino": "Devoluções/Distratos de Vendas"
  },
  {
    "origem": "Doações",
    "destino": "Doações"
  },
  {
    "origem": "Empreitas - Obra",
    "destino": "Empreitas - Obra"
  },
  {
    "origem": "Energia Elétrica - Obra",
    "destino": "ENERGIA ELÉTRICA - OBRA"
  },
  {
    "origem": "EPC(Proteção Coletiva) - Obra",
    "destino": "EPC(Proteção Coletiva) - Obra"
  },
  {
    "origem": "Esquadrias De Alumínio",
    "destino": "Esquadrias De Alumínio"
  },
  {
    "origem": "Esquadrias De Ferro(portões,grades Etc.)",
    "destino": "Esquadrias De Ferro(portões,grades Etc.)"
  },
  {
    "origem": "Esquadrias De Madeira",
    "destino": "Esquadrias De Madeira"
  },
  {
    "origem": "Estacionamento e Condução - Adm",
    "destino": "Estacionamento e Condução - Adm"
  },
  {
    "origem": "Estacionamento e Conduções - Obra",
    "destino": "Estacionamento e Conduções - Obra"
  },
  {
    "origem": "Estrutura De Concreto",
    "destino": "Estrutura De Concreto"
  },
  {
    "origem": "Fardamentos/EPI - Obra",
    "destino": "Fardamentos/EPI - Obra"
  },
  {
    "origem": "Férias e Adicional - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Ferramentas",
    "destino": "Ferramentas"
  },
  {
    "origem": "FGTS - Obra",
    "destino": "FGTS - Obra"
  },
  {
    "origem": "Fretes - Obra",
    "destino": "Fretes - Obra"
  },
  {
    "origem": "Fundações",
    "destino": "Fundações"
  },
  {
    "origem": "Gratificações - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "ICMS(diferencial Aliquota)",
    "destino": "ICMS(diferencial Aliquota)"
  },
  {
    "origem": "Impermeabilização(MAT+M.O.)",
    "destino": "Impermeabilização(MAT+M.O.)"
  },
  {
    "origem": "INSS - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Instalação Do Canteiro",
    "destino": "Instalação Do Canteiro"
  },
  {
    "origem": "Instalações Elétricas(MAT+M.O.)",
    "destino": "Instalações Elétricas(MAT+M.O.)"
  },
  {
    "origem": "Instalações Hidrossanitárias(MAT+M.O.)",
    "destino": "Instalações Hidrossanitárias(MAT+M.O.)"
  },
  {
    "origem": "Instalações Incêndio(MAT+M.O.)",
    "destino": "Instalações Incêndio(MAT+M.O.)"
  },
  {
    "origem": "IPTU - Obra",
    "destino": "IPTU - Obra"
  },
  {
    "origem": "IPTU das Unidades Finalizadas",
    "destino": "IPTU das Unidades Finalizadas"
  },
  {
    "origem": "IRPJ",
    "destino": "IRPJ"
  },
  {
    "origem": "IRRF S/folha - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "ITBI",
    "destino": "Licenças e Legalizações"
  },
  {
    "origem": "Licenças e Legalizações",
    "destino": "Licenças e Legalizações"
  },
  {
    "origem": "Limpeza De Obra",
    "destino": "Limpeza De Obra"
  },
  {
    "origem": "Manutenção e Conservação de Veículos",
    "destino": "Manutenção e Conservação de Veículos"
  },
  {
    "origem": "Materiais De Escritório E Informática - Obra",
    "destino": "Materiais De Escritório E Informática - Obra"
  },
  {
    "origem": "Material De Copa E Limpeza - Obra",
    "destino": "Limpeza De Obra"
  },
  {
    "origem": "Material De Escritório e Informática - Adm",
    "destino": "Material De Escritório e Informática - Adm"
  },
  {
    "origem": "Material Gráfico",
    "destino": "Cópias E Impressões - Obra"
  },
  {
    "origem": "Multas a Autos Administrativos e Danos",
    "destino": "Multas a Autos Administrativos e Danos"
  },
  {
    "origem": "Participações de Resultado - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Pintura (MAT+M.O.)",
    "destino": "Pintura (MAT+M.O.)"
  },
  {
    "origem": "PIS",
    "destino": "PIS"
  },
  {
    "origem": "Pisos(MAT+M.O.)",
    "destino": "Pisos(MAT+M.O.)"
  },
  {
    "origem": "Produção (Folha) - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Projetos(arq./inst./estrutural Etc)",
    "destino": "Projetos(arq./inst./estrutural Etc)"
  },
  {
    "origem": "Publicidade e Propaganda",
    "destino": "Publicidade e Propaganda"
  },
  {
    "origem": "Reformas e Instalações",
    "destino": "Reformas e Instalações"
  },
  {
    "origem": "Rendimentos Aplicações",
    "destino": "Rendimentos Aplicações"
  },
  {
    "origem": "Repasse Enviado Central>Obras",
    "destino": "Repasse Enviado Central>Obras"
  },
  {
    "origem": "Salários - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Seguro Vida/ Programas De Saúde - Obra",
    "destino": "Salários - Obra"
  },
  {
    "origem": "Serviço de Segurança de Canteiro",
    "destino": "Serviço de Segurança de Canteiro"
  },
  {
    "origem": "Serviço de Segurança e Apoio - Adm",
    "destino": "Serviço de Segurança e Apoio - Adm"
  },
  {
    "origem": "Servicos De Advocacia",
    "destino": "Servicos De Advocacia"
  },
  {
    "origem": "Serviços De Consultoria",
    "destino": "Serviços De Consultoria"
  },
  {
    "origem": "Sondagem E Topografia",
    "destino": "Sondagem E Topografia"
  },
  {
    "origem": "Stand De Vendas/Ap.Decorado(Construção)",
    "destino": "Stand De Vendas/Ap.Decorado(Construção)"
  },
  {
    "origem": "Stand e Apto.decorado(conservação)",
    "destino": "Stand e Apto.decorado(conservação)"
  },
  {
    "origem": "Tarifas Bancárias",
    "destino": "Tarifas Bancárias"
  },
  {
    "origem": "Taxas Públicas e Cartóriais - Adm",
    "destino": "Taxas Públicas e Cartóriais - Adm"
  },
  {
    "origem": "Telefonia/Internet - Obra",
    "destino": "Telefonia/Internet - Obra"
  },
  {
    "origem": "Terraplanagem",
    "destino": "Terraplanagem"
  },
  {
    "origem": "Transporte de Pessoal - Obra",
    "destino": "Transporte de Pessoal - Obra"
  }
];

// Todas as linhas da DRE da aba RESUMO ORÇAMENTO X REAL
export const ATRIUM_DRE_LINES: DreItem[] = [
  {
    "id": "dre-4",
    "rowNumber": 4,
    "name": "RECEITAS",
    "orcado": 55206000,
    "realizado": 4789007.29,
    "variacao": -50416992.71,
    "percentRealizado": 8.67,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "receita",
    "subgroup": ""
  },
  {
    "id": "dre-5",
    "rowNumber": 5,
    "name": "RECEITAS OPERACIONAIS",
    "orcado": 55206000,
    "realizado": 4789007.29,
    "variacao": -50416992.71,
    "percentRealizado": 8.67,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "receita",
    "subgroup": "RECEITAS OPERACIONAIS"
  },
  {
    "id": "dre-6",
    "rowNumber": 6,
    "name": "RECEITA DE VENDAS DE IMÓVEIS",
    "orcado": 55206000,
    "realizado": 4789007.29,
    "variacao": -50416992.71,
    "percentRealizado": 8.67,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "receita",
    "subgroup": "RECEITAS OPERACIONAIS"
  },
  {
    "id": "dre-7",
    "rowNumber": 7,
    "name": "RECEITA DE OBRAS PÚBLICAS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "receita",
    "subgroup": "RECEITAS OPERACIONAIS"
  },
  {
    "id": "dre-8",
    "rowNumber": 8,
    "name": "RECEITA DE REFORMAS PERSONALIZADAS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "receita",
    "subgroup": "RECEITAS OPERACIONAIS"
  },
  {
    "id": "dre-9",
    "rowNumber": 9,
    "name": "DEDUÇÕES DA RECEITA",
    "orcado": 2208240,
    "realizado": 228373.95,
    "variacao": -1979866.05,
    "percentRealizado": 10.34,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "deducao",
    "subgroup": ""
  },
  {
    "id": "dre-10",
    "rowNumber": 10,
    "name": "IMPOSTO SOBRE RECEITA",
    "orcado": 2208240,
    "realizado": 185048.95,
    "variacao": -2023191.05,
    "percentRealizado": 8.38,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "IMPOSTO SOBRE RECEITA"
  },
  {
    "id": "dre-11",
    "rowNumber": 11,
    "name": "PIS",
    "orcado": 204577.2638169522,
    "realizado": 17143.43,
    "variacao": -187433.83,
    "percentRealizado": 8.38,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "IMPOSTO SOBRE RECEITA"
  },
  {
    "id": "dre-12",
    "rowNumber": 12,
    "name": "COFINS",
    "orcado": 945467.8851709235,
    "realizado": 79229.54,
    "variacao": -866238.35,
    "percentRealizado": 8.38,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "IMPOSTO SOBRE RECEITA"
  },
  {
    "id": "dre-13",
    "rowNumber": 13,
    "name": "CSLL",
    "orcado": 362154.25023919344,
    "realizado": 30348.27,
    "variacao": -331805.98,
    "percentRealizado": 8.38,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "IMPOSTO SOBRE RECEITA"
  },
  {
    "id": "dre-14",
    "rowNumber": 14,
    "name": "IRPJ",
    "orcado": 696040.6007729305,
    "realizado": 58327.71,
    "variacao": -637712.89,
    "percentRealizado": 8.38,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "IMPOSTO SOBRE RECEITA"
  },
  {
    "id": "dre-15",
    "rowNumber": 15,
    "name": "ISS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "IMPOSTO SOBRE RECEITA"
  },
  {
    "id": "dre-16",
    "rowNumber": 16,
    "name": "DEVOLUÇÕES E CANCELAMENTOS",
    "orcado": 0,
    "realizado": 43325,
    "variacao": 43325,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "DEVOLUÇÕES E CANCELAMENTOS"
  },
  {
    "id": "dre-17",
    "rowNumber": 17,
    "name": "DEVOLUÇÕES/DISTRATOS DE VENDAS",
    "orcado": 0,
    "realizado": 43325,
    "variacao": 43325,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "deducao",
    "subgroup": "DEVOLUÇÕES E CANCELAMENTOS"
  },
  {
    "id": "dre-18",
    "rowNumber": 18,
    "name": "CUSTOS (ORÇAMENTO APROVADO DA OBRA)",
    "orcado": 25705359.47,
    "realizado": 11292416.61,
    "variacao": -14412942.86,
    "percentRealizado": 43.93,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": ""
  },
  {
    "id": "dre-19",
    "rowNumber": 19,
    "name": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA",
    "orcado": 15715662.400299998,
    "realizado": 6764032.26,
    "variacao": -8951630.14,
    "percentRealizado": 43.04,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-20",
    "rowNumber": 20,
    "name": "ALVENARIA E PAINÉIS",
    "orcado": 487389.75,
    "realizado": 250252.05000000002,
    "variacao": -237137.7,
    "percentRealizado": 51.35,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-21",
    "rowNumber": 21,
    "name": "COBERTA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-22",
    "rowNumber": 22,
    "name": "CONTROLE TECNOLÓGICO",
    "orcado": 36000,
    "realizado": 68791.50999999998,
    "variacao": 32791.51,
    "percentRealizado": 191.09,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-23",
    "rowNumber": 23,
    "name": "DESMATAMENTO/DEMOLIÇÃO",
    "orcado": 67500,
    "realizado": 52200,
    "variacao": -15300,
    "percentRealizado": 77.33,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-24",
    "rowNumber": 24,
    "name": "DRENAGEM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-25",
    "rowNumber": 25,
    "name": "ELEVADORES",
    "orcado": 700000,
    "realizado": 0,
    "variacao": -700000,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-26",
    "rowNumber": 26,
    "name": "ESQUADRIAS DE ALUMÍNIO",
    "orcado": 1142203.4,
    "realizado": 594.4,
    "variacao": -1141609,
    "percentRealizado": 0.05,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-27",
    "rowNumber": 27,
    "name": "ESQUADRIAS DE FERRO(PORTÕES,GRADES ETC.)",
    "orcado": 0,
    "realizado": 303.87,
    "variacao": 303.87,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-28",
    "rowNumber": 28,
    "name": "ESQUADRIAS DE MADEIRA",
    "orcado": 348113.8,
    "realizado": 1300,
    "variacao": -346813.8,
    "percentRealizado": 0.37,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-29",
    "rowNumber": 29,
    "name": "ESTRUTURA DE CONCRETO",
    "orcado": 5579917.04,
    "realizado": 4477883.77,
    "variacao": -1102033.27,
    "percentRealizado": 80.25,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-30",
    "rowNumber": 30,
    "name": "FORROS",
    "orcado": 128143.925,
    "realizado": 0,
    "variacao": -128143.92,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-31",
    "rowNumber": 31,
    "name": "FUNDAÇÕES",
    "orcado": 1829815.5417999998,
    "realizado": 1156233.08,
    "variacao": -673582.46,
    "percentRealizado": 63.19,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-32",
    "rowNumber": 32,
    "name": "IMPERMEABILIZAÇÃO(MAT+M.O.)",
    "orcado": 156828.82,
    "realizado": 2205.5,
    "variacao": -154623.32,
    "percentRealizado": 1.41,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-33",
    "rowNumber": 33,
    "name": "INSTALAÇÃO DO CANTEIRO",
    "orcado": 90795.7,
    "realizado": 148477.51,
    "variacao": 57681.81,
    "percentRealizado": 163.53,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-34",
    "rowNumber": 34,
    "name": "INSTALAÇÕES INCÊNDIO(MAT+M.O.)",
    "orcado": 70000,
    "realizado": 2327.04,
    "variacao": -67672.96,
    "percentRealizado": 3.32,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-35",
    "rowNumber": 35,
    "name": "INSTALAÇÃO DE AR CONDICIONADO(MAT+M.O.)",
    "orcado": 150000,
    "realizado": 2819.16,
    "variacao": -147180.84,
    "percentRealizado": 1.88,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-36",
    "rowNumber": 36,
    "name": "INSTALAÇÕES DE GÁS(MAT+M.O.)",
    "orcado": 80000,
    "realizado": 393.3,
    "variacao": -79606.7,
    "percentRealizado": 0.49,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-37",
    "rowNumber": 37,
    "name": "INSTALAÇÕES ELÉTRICAS(MAT+M.O.)",
    "orcado": 550000,
    "realizado": 18225.210000000003,
    "variacao": -531774.79,
    "percentRealizado": 3.31,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-38",
    "rowNumber": 38,
    "name": "INSTALAÇÕES HIDROSSANITÁRIAS(MAT+M.O.)",
    "orcado": 650000,
    "realizado": 42125.60999999999,
    "variacao": -607874.39,
    "percentRealizado": 6.48,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-39",
    "rowNumber": 39,
    "name": "INSTALAÇÕES MECÂNICAS(MAT+M.O.)",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-40",
    "rowNumber": 40,
    "name": "INSTALAÇÕES TELEFÔNICAS(MAT+M.O.)",
    "orcado": 60000,
    "realizado": 0,
    "variacao": -60000,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-41",
    "rowNumber": 41,
    "name": "LIMPEZA DE OBRA",
    "orcado": 30225.6,
    "realizado": 28620.409999999993,
    "variacao": -1605.19,
    "percentRealizado": 94.69,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-42",
    "rowNumber": 42,
    "name": "LOUÇAS E METAIS",
    "orcado": 193201.5,
    "realizado": 0,
    "variacao": -193201.5,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-43",
    "rowNumber": 43,
    "name": "MÁRMORES E GRANITOS",
    "orcado": 88133.8,
    "realizado": 0,
    "variacao": -88133.8,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-44",
    "rowNumber": 44,
    "name": "PAISAGISMO/URBANISMO/DECORAÇÃO/ACESSÓRIOS",
    "orcado": 446475,
    "realizado": 0,
    "variacao": -446475,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-45",
    "rowNumber": 45,
    "name": "PAVIMENTAÇÃO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-46",
    "rowNumber": 46,
    "name": "PINTURA (MAT+M.O.)",
    "orcado": 201902.0234,
    "realizado": 4878.99,
    "variacao": -197023.03,
    "percentRealizado": 2.42,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-47",
    "rowNumber": 47,
    "name": "PISOS(MAT+M.O.)",
    "orcado": 835164.938,
    "realizado": 24427.059999999998,
    "variacao": -810737.88,
    "percentRealizado": 2.92,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-48",
    "rowNumber": 48,
    "name": "PRÉ-MOLDADOS",
    "orcado": 5678.3025,
    "realizado": 0,
    "variacao": -5678.3,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-49",
    "rowNumber": 49,
    "name": "PROJETOS(ARQ./INST./ESTRUTURAL ETC)",
    "orcado": 323000,
    "realizado": 353232.63000000024,
    "variacao": 30232.63,
    "percentRealizado": 109.36,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-50",
    "rowNumber": 50,
    "name": "REVESTIMENTO EXTERNO",
    "orcado": 687619.8996,
    "realizado": 5999.4,
    "variacao": -681620.5,
    "percentRealizado": 0.87,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-51",
    "rowNumber": 51,
    "name": "REVESTIMENTO INTERNO",
    "orcado": 543245.96,
    "realizado": 98,
    "variacao": -543147.96,
    "percentRealizado": 0.02,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-52",
    "rowNumber": 52,
    "name": "SONDAGEM E TOPOGRAFIA",
    "orcado": 8000,
    "realizado": 19918.64,
    "variacao": 11918.64,
    "percentRealizado": 248.98,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-53",
    "rowNumber": 53,
    "name": "TERRAPLANAGEM",
    "orcado": 176307.4,
    "realizado": 1680,
    "variacao": -174627.4,
    "percentRealizado": 0.95,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-54",
    "rowNumber": 54,
    "name": "ICMS(DIFERENCIAL ALIQUOTA)",
    "orcado": 0,
    "realizado": 14390.48,
    "variacao": 14390.48,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-55",
    "rowNumber": 55,
    "name": "STAND DE VENDAS/AP.DECORADO(CONSTRUÇÃO)",
    "orcado": 50000,
    "realizado": 86654.64000000003,
    "variacao": 36654.64,
    "percentRealizado": 173.31,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "MATERIAIS E SERVIÇOS DE EXECUÇÃO DE OBRA"
  },
  {
    "id": "dre-56",
    "rowNumber": 56,
    "name": "CUSTO COM MÃO DE OBRA",
    "orcado": 8897338.353500005,
    "realizado": 3730363.0100000044,
    "variacao": -5166975.34,
    "percentRealizado": 41.93,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-57",
    "rowNumber": 57,
    "name": "13º. SALÁRIO - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-58",
    "rowNumber": 58,
    "name": "BENEFICIOS DE PESSOAL - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-59",
    "rowNumber": 59,
    "name": "CURSOS E TREINAMENTOS",
    "orcado": 10000,
    "realizado": 560,
    "variacao": -9440,
    "percentRealizado": 5.6,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-60",
    "rowNumber": 60,
    "name": "FARDAMENTOS/EPI - OBRA",
    "orcado": 57600,
    "realizado": 71355.09000000001,
    "variacao": 13755.09,
    "percentRealizado": 123.88,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-61",
    "rowNumber": 61,
    "name": "FÉRIAS E ADICIONAL - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-62",
    "rowNumber": 62,
    "name": "FGTS - OBRA",
    "orcado": 0,
    "realizado": 112760.69,
    "variacao": 112760.69,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-63",
    "rowNumber": 63,
    "name": "GRATIFICAÇÕES - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-64",
    "rowNumber": 64,
    "name": "INSS - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-65",
    "rowNumber": 65,
    "name": "IRRF S/FOLHA - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-66",
    "rowNumber": 66,
    "name": "PARTICIPAÇÕES DE RESULTADO - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-67",
    "rowNumber": 67,
    "name": "PRODUÇÃO (FOLHA) - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-68",
    "rowNumber": 68,
    "name": "ALIMENTAÇÃO DE PESSOAL - OBRA",
    "orcado": 502524,
    "realizado": 283812.6599999999,
    "variacao": -218711.34,
    "percentRealizado": 56.48,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-69",
    "rowNumber": 69,
    "name": "ADMISSÕES E RESCISÕES - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-70",
    "rowNumber": 70,
    "name": "SALÁRIOS - OBRA",
    "orcado": 7821868.057500004,
    "realizado": 3097098.120000005,
    "variacao": -4724769.94,
    "percentRealizado": 39.6,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-71",
    "rowNumber": 71,
    "name": "SEGURO VIDA/ PROGRAMAS DE SAÚDE - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-72",
    "rowNumber": 72,
    "name": "TRANSPORTE DE PESSOAL - OBRA",
    "orcado": 320760,
    "realizado": 98659.37999999999,
    "variacao": -222100.62,
    "percentRealizado": 30.76,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-73",
    "rowNumber": 73,
    "name": "CONTRIBUIÇÕES SINDICAIS - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-74",
    "rowNumber": 74,
    "name": "EMPREITAS - OBRA",
    "orcado": 0,
    "realizado": 45,
    "variacao": 45,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-75",
    "rowNumber": 75,
    "name": "EPC(PROTEÇÃO COLETIVA) - OBRA",
    "orcado": 184586.296,
    "realizado": 66072.07000000002,
    "variacao": -118514.23,
    "percentRealizado": 35.79,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-76",
    "rowNumber": 76,
    "name": "HORAS EXTRA - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTO COM MÃO DE OBRA"
  },
  {
    "id": "dre-77",
    "rowNumber": 77,
    "name": "CUSTOS ADMINISTRATIVO DE OBRA",
    "orcado": 925480,
    "realizado": 600933.62,
    "variacao": -324546.38,
    "percentRealizado": 64.93,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-78",
    "rowNumber": 78,
    "name": "ALUGUEL E MANUT. DE MAQ. EQUIP E MÓVEIS - OBRA",
    "orcado": 744700,
    "realizado": 455255.16000000003,
    "variacao": -289444.84,
    "percentRealizado": 61.13,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-79",
    "rowNumber": 79,
    "name": "AGUA & ESGOTO - OBRA",
    "orcado": 30600,
    "realizado": 67349.68000000001,
    "variacao": 36749.68,
    "percentRealizado": 220.1,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-80",
    "rowNumber": 80,
    "name": "CÓPIAS E IMPRESSÕES - OBRA",
    "orcado": 10000,
    "realizado": 4582.05,
    "variacao": -5417.95,
    "percentRealizado": 45.82,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-81",
    "rowNumber": 81,
    "name": "ENERGIA ELÉTRICA - OBRA",
    "orcado": 72000,
    "realizado": 30895.19,
    "variacao": -41104.81,
    "percentRealizado": 42.91,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-82",
    "rowNumber": 82,
    "name": "FRETES - OBRA",
    "orcado": 50000,
    "realizado": 15464.159999999998,
    "variacao": -34535.84,
    "percentRealizado": 30.93,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-83",
    "rowNumber": 83,
    "name": "ALUGUEL - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-84",
    "rowNumber": 84,
    "name": "TELEFONIA/INTERNET - OBRA",
    "orcado": 4500,
    "realizado": 2360.1499999999996,
    "variacao": -2139.85,
    "percentRealizado": 52.45,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-85",
    "rowNumber": 85,
    "name": "MATERIAIS DE ESCRITÓRIO E INFORMÁTICA - OBRA",
    "orcado": 0,
    "realizado": 1481.63,
    "variacao": 1481.63,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-86",
    "rowNumber": 86,
    "name": "ESTACIONAMENTO E CONDUÇÕES - OBRA",
    "orcado": 0,
    "realizado": 10357.459999999997,
    "variacao": 10357.46,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-87",
    "rowNumber": 87,
    "name": "COMPESAÇÃO DE OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-88",
    "rowNumber": 88,
    "name": "MATERIAL DE COPA E LIMPEZA - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-89",
    "rowNumber": 89,
    "name": "SERVIÇO DE SEGURANÇA DE CANTEIRO",
    "orcado": 13680,
    "realizado": 13188.140000000003,
    "variacao": -491.86,
    "percentRealizado": 96.4,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS ADMINISTRATIVO DE OBRA"
  },
  {
    "id": "dre-90",
    "rowNumber": 90,
    "name": "CUSTOS COM TERRENOS E LEGALIZAÇÕES",
    "orcado": 60140,
    "realizado": 57574.71000000001,
    "variacao": -2565.29,
    "percentRealizado": 95.73,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-91",
    "rowNumber": 91,
    "name": "AQUISIÇÃO DE TERRENOS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-92",
    "rowNumber": 92,
    "name": "ITBI",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-93",
    "rowNumber": 93,
    "name": "OUTORGA/OPERAÇÃO URBANA/SOLO CRIADO",
    "orcado": 20000,
    "realizado": 0,
    "variacao": -20000,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-94",
    "rowNumber": 94,
    "name": "IPTU - OBRA",
    "orcado": 40140,
    "realizado": 57574.71000000001,
    "variacao": 17434.71,
    "percentRealizado": 143.43,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-95",
    "rowNumber": 95,
    "name": "ALVARAS E LICENÇAS - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-96",
    "rowNumber": 96,
    "name": "CUSTAS CARTÓRIAIS - OBRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-97",
    "rowNumber": 97,
    "name": "LAUDEMIO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "custo_obra",
    "subgroup": "CUSTOS COM TERRENOS E LEGALIZAÇÕES"
  },
  {
    "id": "dre-98",
    "rowNumber": 98,
    "name": "DESPESAS",
    "orcado": 3649890,
    "realizado": 2666993.09,
    "variacao": -982896.91,
    "percentRealizado": 73.07,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": ""
  },
  {
    "id": "dre-99",
    "rowNumber": 99,
    "name": "DESPESAS ADMINISTRATIVAS",
    "orcado": 61500,
    "realizado": 284248.99999999994,
    "variacao": 222749,
    "percentRealizado": 462.19,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-100",
    "rowNumber": 100,
    "name": "TARIFAS BANCÁRIAS",
    "orcado": 0,
    "realizado": 423.8999999999991,
    "variacao": 423.9,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-101",
    "rowNumber": 101,
    "name": "SINDICATOS E ASSOCIAÇÕES DE CLASSE - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-102",
    "rowNumber": 102,
    "name": "LICENÇAS E LEGALIZAÇÕES",
    "orcado": 61500,
    "realizado": 125155.68000000001,
    "variacao": 63655.68,
    "percentRealizado": 203.51,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-103",
    "rowNumber": 103,
    "name": "MULTAS A AUTOS ADMINISTRATIVOS E DANOS",
    "orcado": 0,
    "realizado": 123044.12999999996,
    "variacao": 123044.13,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-104",
    "rowNumber": 104,
    "name": "TAXAS PÚBLICAS E CARTÓRIAIS - ADM",
    "orcado": 0,
    "realizado": 22627.2,
    "variacao": 22627.2,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-105",
    "rowNumber": 105,
    "name": "DESPESAS COM MATERIAL DE COPA E LIMPEZA - ADM",
    "orcado": 0,
    "realizado": 2413.6899999999996,
    "variacao": 2413.69,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-106",
    "rowNumber": 106,
    "name": "CORREIOS/MALOTE - ADM",
    "orcado": 0,
    "realizado": 343.76,
    "variacao": 343.76,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-107",
    "rowNumber": 107,
    "name": "ALUGUÉIS E CONDOMÍNIOS - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-108",
    "rowNumber": 108,
    "name": "ESTACIONAMENTO E CONDUÇÃO - ADM",
    "orcado": 0,
    "realizado": 6690.54,
    "variacao": 6690.54,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-109",
    "rowNumber": 109,
    "name": "MANUTENÇÃO PREDIAIS - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-110",
    "rowNumber": 110,
    "name": "MATERIAL DE ESCRITÓRIO E INFORMÁTICA - ADM",
    "orcado": 0,
    "realizado": 3550.1,
    "variacao": 3550.1,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-111",
    "rowNumber": 111,
    "name": "PERIÓDICOS & PUBLICAÇÕES",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-112",
    "rowNumber": 112,
    "name": "TELEFONIA/INTERNET - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-113",
    "rowNumber": 113,
    "name": "VIAGENS E ESTADIA ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-114",
    "rowNumber": 114,
    "name": "SEGUROS PATRIMONIAIS - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-115",
    "rowNumber": 115,
    "name": "FRETE - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-116",
    "rowNumber": 116,
    "name": "ÁGUA/ESGOTO - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-117",
    "rowNumber": 117,
    "name": "ALUGUEL MANUT DE MAQ, EQUIP E MOVÉIS - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-118",
    "rowNumber": 118,
    "name": "IPTU - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-119",
    "rowNumber": 119,
    "name": "LICENÇAS E MANUTENÇÃO DE SISTEMA - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-120",
    "rowNumber": 120,
    "name": "ENERGIA ELÉTRICA - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-121",
    "rowNumber": 121,
    "name": "CÓPIAS E IMPRESSÕES - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS ADMINISTRATIVAS"
  },
  {
    "id": "dre-122",
    "rowNumber": 122,
    "name": "DESPESAS COM DIRETORIA",
    "orcado": 0,
    "realizado": 3000,
    "variacao": 3000,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM DIRETORIA"
  },
  {
    "id": "dre-123",
    "rowNumber": 123,
    "name": "PRÓ-LABORE",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM DIRETORIA"
  },
  {
    "id": "dre-124",
    "rowNumber": 124,
    "name": "BENEFÍCIOS E RETIRADAS DA DIRETORIA",
    "orcado": 0,
    "realizado": 3000,
    "variacao": 3000,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM DIRETORIA"
  },
  {
    "id": "dre-125",
    "rowNumber": 125,
    "name": "DESPESAS COM PERDAS",
    "orcado": 0,
    "realizado": 829.3,
    "variacao": 829.3,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PERDAS"
  },
  {
    "id": "dre-126",
    "rowNumber": 126,
    "name": "DESPESAS COM PERDAS",
    "orcado": 0,
    "realizado": 829.3,
    "variacao": 829.3,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PERDAS"
  },
  {
    "id": "dre-127",
    "rowNumber": 127,
    "name": "DESPESAS COM PESSOAL ADM",
    "orcado": 0,
    "realizado": 376555.4499999999,
    "variacao": 376555.45,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-128",
    "rowNumber": 128,
    "name": "CONFRATERNIZAÇÕES E EVENTOS INTERNOS ADM",
    "orcado": 0,
    "realizado": 1475,
    "variacao": 1475,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-129",
    "rowNumber": 129,
    "name": "SALARIOS DO ADM",
    "orcado": 0,
    "realizado": 375080.4499999999,
    "variacao": 375080.45,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-130",
    "rowNumber": 130,
    "name": "GRATIFICAÇÕES DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-131",
    "rowNumber": 131,
    "name": "FÉRIAS E ADICONAL DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-132",
    "rowNumber": 132,
    "name": "13º SALÁRIO DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-133",
    "rowNumber": 133,
    "name": "BOLSA DE ESTÁGIO DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-134",
    "rowNumber": 134,
    "name": "ADMISSÕES E RESCISÕES DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-135",
    "rowNumber": 135,
    "name": "INSS DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-136",
    "rowNumber": 136,
    "name": "FGTS DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-137",
    "rowNumber": 137,
    "name": "CONTRIBUIÇÕES SINDICAIS DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-138",
    "rowNumber": 138,
    "name": "TRANSPORTE DE PESSOAL DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-139",
    "rowNumber": 139,
    "name": "ALIMENTAÇÃO DE PESSOAL DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-140",
    "rowNumber": 140,
    "name": "FARDAMENTO E EPI'S DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-141",
    "rowNumber": 141,
    "name": "CURSO E TREINAMENTOS DO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-142",
    "rowNumber": 142,
    "name": "SERVIÇOS DE SEGURANÇA E MEDICINA DO TRABALHO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-143",
    "rowNumber": 143,
    "name": "BENEFÍCIO DE PESSOAL ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-144",
    "rowNumber": 144,
    "name": "IRRF S/FOLHA E FÉRIAS - ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-145",
    "rowNumber": 145,
    "name": "PARTICIPAÇÃO DE RESULTADO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PESSOAL ADM"
  },
  {
    "id": "dre-146",
    "rowNumber": 146,
    "name": "DESPESAS COM PÓS OBRA",
    "orcado": 0,
    "realizado": 220044.30000000013,
    "variacao": 220044.3,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PÓS OBRA"
  },
  {
    "id": "dre-147",
    "rowNumber": 147,
    "name": "DESPESAS COM OBRAS CONCLUÍDAS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PÓS OBRA"
  },
  {
    "id": "dre-148",
    "rowNumber": 148,
    "name": "TAXA DE COND. DAS UND. FINALIZADAS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PÓS OBRA"
  },
  {
    "id": "dre-149",
    "rowNumber": 149,
    "name": "IPTU DAS UNIDADES FINALIZADAS",
    "orcado": 0,
    "realizado": 220044.30000000013,
    "variacao": 220044.3,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PÓS OBRA"
  },
  {
    "id": "dre-150",
    "rowNumber": 150,
    "name": "MANUTENÇÃO DE GARANTIA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM PÓS OBRA"
  },
  {
    "id": "dre-151",
    "rowNumber": 151,
    "name": "DESPESAS COM SERV. TERCEIRIZADOS",
    "orcado": 0,
    "realizado": 819541.46,
    "variacao": 819541.46,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM SERV. TERCEIRIZADOS"
  },
  {
    "id": "dre-152",
    "rowNumber": 152,
    "name": "DESPACHANTES",
    "orcado": 0,
    "realizado": 2000,
    "variacao": 2000,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM SERV. TERCEIRIZADOS"
  },
  {
    "id": "dre-153",
    "rowNumber": 153,
    "name": "SERVICOS DE ADVOCACIA",
    "orcado": 0,
    "realizado": 669741,
    "variacao": 669741,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM SERV. TERCEIRIZADOS"
  },
  {
    "id": "dre-154",
    "rowNumber": 154,
    "name": "SERVIÇOS DE CONSULTORIA",
    "orcado": 0,
    "realizado": 96200,
    "variacao": 96200,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM SERV. TERCEIRIZADOS"
  },
  {
    "id": "dre-155",
    "rowNumber": 155,
    "name": "SERVIÇOS DE CONTABILIDADE",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM SERV. TERCEIRIZADOS"
  },
  {
    "id": "dre-156",
    "rowNumber": 156,
    "name": "SERVIÇO DE SEGURANÇA E APOIO - ADM",
    "orcado": 0,
    "realizado": 51600.45999999993,
    "variacao": 51600.46,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM SERV. TERCEIRIZADOS"
  },
  {
    "id": "dre-157",
    "rowNumber": 157,
    "name": "SERVIÇOS DE INFORMÁTICA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM SERV. TERCEIRIZADOS"
  },
  {
    "id": "dre-158",
    "rowNumber": 158,
    "name": "DESPESAS COM VEÍCULOS",
    "orcado": 0,
    "realizado": 7977.42,
    "variacao": 7977.42,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM VEÍCULOS"
  },
  {
    "id": "dre-159",
    "rowNumber": 159,
    "name": "COMBUSTÍVEL E LUBRIFICANTES",
    "orcado": 0,
    "realizado": 1915.52,
    "variacao": 1915.52,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM VEÍCULOS"
  },
  {
    "id": "dre-160",
    "rowNumber": 160,
    "name": "MANUTENÇÃO E CONSERVAÇÃO DE VEÍCULOS",
    "orcado": 0,
    "realizado": 6061.900000000001,
    "variacao": 6061.9,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM VEÍCULOS"
  },
  {
    "id": "dre-161",
    "rowNumber": 161,
    "name": "SEGUROS DE VEÍCULOS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM VEÍCULOS"
  },
  {
    "id": "dre-162",
    "rowNumber": 162,
    "name": "MULTAS DE TRÂNSITO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM VEÍCULOS"
  },
  {
    "id": "dre-163",
    "rowNumber": 163,
    "name": "IPVA E LICENCIAMENTO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COM VEÍCULOS"
  },
  {
    "id": "dre-164",
    "rowNumber": 164,
    "name": "DESPESAS COMERCIAIS E MARKETING",
    "orcado": 1104120,
    "realizado": 278054.88999999996,
    "variacao": -826065.11,
    "percentRealizado": 25.18,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-165",
    "rowNumber": 165,
    "name": "PUBLICIDADE E PROPAGANDA",
    "orcado": 1104120,
    "realizado": 234850.62999999998,
    "variacao": -869269.37,
    "percentRealizado": 21.27,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-166",
    "rowNumber": 166,
    "name": "BRINDES",
    "orcado": 0,
    "realizado": 1164.29,
    "variacao": 1164.29,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-167",
    "rowNumber": 167,
    "name": "STAND E APTO.DECORADO(CONSERVAÇÃO)",
    "orcado": 0,
    "realizado": 38191.10999999999,
    "variacao": 38191.11,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-168",
    "rowNumber": 168,
    "name": "VIAGENS E EVENTOS COMERCIAIS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-169",
    "rowNumber": 169,
    "name": "ASSESORIAS DE MARKETING",
    "orcado": 0,
    "realizado": 3000,
    "variacao": 3000,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-170",
    "rowNumber": 170,
    "name": "MATERIAL GRÁFICO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-171",
    "rowNumber": 171,
    "name": "AÇÃO E EVENTOS DE RELACIONAMENTO COMERCIAIS",
    "orcado": 0,
    "realizado": 848.86,
    "variacao": 848.86,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS COMERCIAIS E MARKETING"
  },
  {
    "id": "dre-172",
    "rowNumber": 172,
    "name": "DESPESAS PROCESSUAIS",
    "orcado": 0,
    "realizado": 79827.07,
    "variacao": 79827.07,
    "percentRealizado": 100,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS PROCESSUAIS"
  },
  {
    "id": "dre-173",
    "rowNumber": 173,
    "name": "DEPÓSITO JUDICIAL E CONDENAÇÕES",
    "orcado": 0,
    "realizado": 79724.33,
    "variacao": 79724.33,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS PROCESSUAIS"
  },
  {
    "id": "dre-174",
    "rowNumber": 174,
    "name": "BLOQUEIO/DESBLOQUEIO JUDICIAL",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS PROCESSUAIS"
  },
  {
    "id": "dre-175",
    "rowNumber": 175,
    "name": "CUSTAS PROCESSUAIS",
    "orcado": 0,
    "realizado": 102.74,
    "variacao": 102.74,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS PROCESSUAIS"
  },
  {
    "id": "dre-176",
    "rowNumber": 176,
    "name": "SERV. TERC. PROCESSUAIS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS PROCESSUAIS"
  },
  {
    "id": "dre-177",
    "rowNumber": 177,
    "name": "DESPESAS VARIÁVEIS COM VENDAS",
    "orcado": 2484270,
    "realizado": 596914.2,
    "variacao": -1887355.8,
    "percentRealizado": 24.03,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS VARIÁVEIS COM VENDAS"
  },
  {
    "id": "dre-178",
    "rowNumber": 178,
    "name": "COMISSÃO DE CORRETORES",
    "orcado": 2484270,
    "realizado": 596914.2,
    "variacao": -1887355.8,
    "percentRealizado": 24.03,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS VARIÁVEIS COM VENDAS"
  },
  {
    "id": "dre-179",
    "rowNumber": 179,
    "name": "COMISSÃO EXTRA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "despesa",
    "subgroup": "DESPESAS VARIÁVEIS COM VENDAS"
  },
  {
    "id": "dre-181",
    "rowNumber": 181,
    "name": "(=)RESULTADO OPERACIONAL",
    "orcado": 23749249.246199995,
    "realizado": -9259263.350000001,
    "variacao": -33008512.6,
    "percentRealizado": -38.99,
    "level": 1,
    "isGroup": false,
    "isTotal": true,
    "category": "despesa",
    "subgroup": ""
  },
  {
    "id": "dre-183",
    "rowNumber": 183,
    "name": "RECEITAS FINANCEIRAS",
    "orcado": 0,
    "realizado": 72.75000000000007,
    "variacao": 72.75,
    "percentRealizado": 100,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-184",
    "rowNumber": 184,
    "name": "JUROS E MULTAS AUFERIDOS E TX DE CESSÃO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-185",
    "rowNumber": 185,
    "name": "RENDIMENTOS APLICAÇÕES",
    "orcado": 0,
    "realizado": 72.75000000000007,
    "variacao": 72.75,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-186",
    "rowNumber": 186,
    "name": "OUTRAS RECEITAS NÃO OPERACIONAIS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 2,
    "isGroup": true,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": "OUTRAS RECEITAS NÃO OPERACIONAIS"
  },
  {
    "id": "dre-187",
    "rowNumber": 187,
    "name": "RECEITA COM ALUGUEL",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": "OUTRAS RECEITAS NÃO OPERACIONAIS"
  },
  {
    "id": "dre-188",
    "rowNumber": 188,
    "name": "RECEITA COM RATEIO ADM",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": "OUTRAS RECEITAS NÃO OPERACIONAIS"
  },
  {
    "id": "dre-189",
    "rowNumber": 189,
    "name": "DESPESAS NÃO OPERACIONAIS/FINANCEIRAS",
    "orcado": 0,
    "realizado": 4505,
    "variacao": 4505,
    "percentRealizado": 100,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-190",
    "rowNumber": 190,
    "name": "IOF",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-191",
    "rowNumber": 191,
    "name": "DOAÇÕES",
    "orcado": 0,
    "realizado": 4505,
    "variacao": 4505,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-192",
    "rowNumber": 192,
    "name": "JUROS E MULTAS DE MORA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-193",
    "rowNumber": 193,
    "name": "JUROS E TAXAS DE EMPRÉSTIMOS E FINANCIAMENTOS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-195",
    "rowNumber": 195,
    "name": "(=)RESULTADO NÃO OPERACIONAL",
    "orcado": 0,
    "realizado": -4432.25,
    "variacao": -4432.25,
    "percentRealizado": 100,
    "level": 1,
    "isGroup": false,
    "isTotal": true,
    "category": "financeiro",
    "subgroup": ""
  },
  {
    "id": "dre-197",
    "rowNumber": 197,
    "name": "INVESTIMENTOS - IMOBILIZADO",
    "orcado": 45238.72,
    "realizado": 186278.78000000003,
    "variacao": 141040.06,
    "percentRealizado": 411.77,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-198",
    "rowNumber": 198,
    "name": "AQUISIÇÃO DE MÁQUINAS E EQUIPAMENTOS",
    "orcado": 0,
    "realizado": 128397.68000000001,
    "variacao": 128397.68,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-199",
    "rowNumber": 199,
    "name": "FERRAMENTAS",
    "orcado": 45238.72,
    "realizado": 45081.50000000002,
    "variacao": -157.22,
    "percentRealizado": 99.65,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-200",
    "rowNumber": 200,
    "name": "AQUISIÇÃO DE MÓVEIS E UTENSÍLIOS",
    "orcado": 0,
    "realizado": 129.89000000000001,
    "variacao": 129.89,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-201",
    "rowNumber": 201,
    "name": "AQUISIÇÃO DE COMPUTADORES E PERIFÉRICOS",
    "orcado": 0,
    "realizado": 259.27,
    "variacao": 259.27,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-202",
    "rowNumber": 202,
    "name": "AQUISIÇÃO DE VEÍCULOS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-203",
    "rowNumber": 203,
    "name": "CONSÓRCIO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-204",
    "rowNumber": 204,
    "name": "CONSTRUÇÃO/INVESTIMENTO IMÓVEIS P/LOCAÇÃO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-205",
    "rowNumber": 205,
    "name": "AQUISIÇÃO DE IMÓVEIS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-206",
    "rowNumber": 206,
    "name": "REFORMAS E INSTALAÇÕES",
    "orcado": 0,
    "realizado": 12410.439999999999,
    "variacao": 12410.44,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-207",
    "rowNumber": 207,
    "name": "INVESTIMENTOS - INTANGIVEIS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-208",
    "rowNumber": 208,
    "name": "REGISTRO DE MARCAS E PATENTES",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-209",
    "rowNumber": 209,
    "name": "COMPRA DE SOFTWARE",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-210",
    "rowNumber": 210,
    "name": "VENDA DE IMOBILIZADO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-211",
    "rowNumber": 211,
    "name": "VENDA DE IMOBILIZADOS E MAT. DE ESTOQUE",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-213",
    "rowNumber": 213,
    "name": "(=)RESULTADO DE INVESTIMENTO",
    "orcado": -45238.72,
    "realizado": -186278.78000000003,
    "variacao": -141040.06,
    "percentRealizado": 100,
    "level": 1,
    "isGroup": false,
    "isTotal": true,
    "category": "investimento",
    "subgroup": ""
  },
  {
    "id": "dre-215",
    "rowNumber": 215,
    "name": "EMPRESTIMOS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-216",
    "rowNumber": 216,
    "name": "EMPRÉSTIMO TOMADO (+)",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-217",
    "rowNumber": 217,
    "name": "EMPRESTIMOS CONCEDIDOS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-218",
    "rowNumber": 218,
    "name": "PAGAMENTO DE EMPRÉSTIMO TOMADO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-219",
    "rowNumber": 219,
    "name": "PARCELAMENTO DE IMPOSTO E REFIS",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-220",
    "rowNumber": 220,
    "name": "MUTUÁRIOS CEF",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-221",
    "rowNumber": 221,
    "name": "RECEBIMENTO DE EMPRÉSTIMOS CEDIDO (+)",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-222",
    "rowNumber": 222,
    "name": "MOVIMENTAÇÃO DE CAPITAL",
    "orcado": 0,
    "realizado": 500,
    "variacao": 500,
    "percentRealizado": 100,
    "level": 1,
    "isGroup": true,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-223",
    "rowNumber": 223,
    "name": "MOVIMENTAÇÕES TRANSITÓRIAS - RECEITA CLIENTES",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-224",
    "rowNumber": 224,
    "name": "APORTE DE CAPITAL",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-225",
    "rowNumber": 225,
    "name": "RETIRADA DE CAPITAL",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-226",
    "rowNumber": 226,
    "name": "DISTRIBUIÇÃO DE LUCRO",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-227",
    "rowNumber": 227,
    "name": "TRANSFERÊNCIA ENTRE CONTAS - ENTRADA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-228",
    "rowNumber": 228,
    "name": "TRANSFERÊNCIA ENTRE CONTAS - SAÍDA",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-229",
    "rowNumber": 229,
    "name": "Repasse Enviado Central>Obras",
    "orcado": 0,
    "realizado": 500,
    "variacao": 500,
    "percentRealizado": 100,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-230",
    "rowNumber": 230,
    "name": "REPASSE ENVIADO OBRAS > CENTRAL",
    "orcado": 0,
    "realizado": 0,
    "variacao": 0,
    "percentRealizado": 0,
    "level": 3,
    "isGroup": false,
    "isTotal": false,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-232",
    "rowNumber": 232,
    "name": "(=)RESULTADO FINANCIAMENTOS",
    "orcado": 0,
    "realizado": 500,
    "variacao": 500,
    "percentRealizado": 100,
    "level": 1,
    "isGroup": false,
    "isTotal": true,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-234",
    "rowNumber": 234,
    "name": "(=) RESULTADO DE FLUXO DE CAIXA",
    "orcado": 23704010.526199996,
    "realizado": -9449474.38,
    "variacao": -33153484.91,
    "percentRealizado": -39.86,
    "level": 1,
    "isGroup": false,
    "isTotal": true,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-236",
    "rowNumber": 236,
    "name": "CUSTO TOTAL",
    "orcado": 31501989.473800004,
    "realizado": 14239627.170000004,
    "variacao": -17262362.3,
    "percentRealizado": 45.2,
    "level": 1,
    "isGroup": false,
    "isTotal": true,
    "category": "financiamento",
    "subgroup": ""
  },
  {
    "id": "dre-237",
    "rowNumber": 237,
    "name": "RESULTADO",
    "orcado": 25705359.473800004,
    "realizado": -4200000.000000002,
    "variacao": -29905359.47,
    "percentRealizado": -16.34,
    "level": 1,
    "isGroup": false,
    "isTotal": true,
    "category": "financiamento",
    "subgroup": ""
  }
];

/**
 * Verifica se uma conta ou código pertence ao Orçamento da Obra (Construção Civil)
 * Retorna false para contas de Receitas, Impostos, Marketing, Vendas e Despesas Corporativas da Sede
 */
export function isConstructionAccount(accountName: string): boolean {
  if (!accountName) return false;
  const norm = accountName.trim().toLowerCase();
  
  // Lista explícita de termos fora da obra
  const nonConstructionBlacklist = [
    'pis', 'cofins', 'irpj', 'csll', 'receita', 'vendas', 'corretores', 'marketing',
    'propaganda', 'advocacia', 'tarifas', 'diretoria', 'distratos'
  ];
  if (nonConstructionBlacklist.some(term => norm === term || norm.startsWith(term + ' ') || norm.endsWith(' ' + term))) {
    return false;
  }

  return ATRIUM_OBRA_ACCOUNTS.some((a) => a.trim().toLowerCase() === norm);
}
